site_name: SITE_NAME
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - navigation.prune # 折叠
    - search.suggest
    - search.highlight
    - content.code.copy
    # Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
  language: zh

# 这里写目录
nav:
  - 主页: index.md

markdown_extensions:
  # 支持个性化定制
  # Reference: https://squidfunk.github.io/mkdocs-material/reference/
  #--------------------分割线--------------------
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Formatting: Highlight, Sub & Keyboard Keys.
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # attr_list
  - markdown.extensions.attr_list
  # List
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
    
extra:
  homepage: HOMEPAGE 
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: YOUR_BILIBILI_LINK
      name: Bilibili | YOUR_NAME # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: YOUR_GITHUB_LINK
      name: GitHub | YOUR_NAME 
    - icon: simple/githubactions
      link: THIS_REPO_ACTION
      name: GitHub Actions

## [bottom-left corner]
copyright: Copyright &copy; 2023-现在 YOUR_NAME # 左下角的版权声明
